"use strict";
exports.__esModule = true;
var getUA_1 = require("./getUA");
exports.getUA = getUA_1.getUA;
var IE_1 = require("./IE");
exports.isIE = IE_1.isIE;
exports.isEdge = IE_1.isEdge;
var addListener_1 = require("./addListener");
exports.addListener = addListener_1.addListener;
var removeListener_1 = require("./removeListener");
exports.removeListener = removeListener_1.removeListener;
var getType_1 = require("./getType");
exports.getType = getType_1.getType;
